[[pp_lib]]
arch = "x86_64"
os = "linux"
git-tree-sha1 = "320e20d04bc17de8150ec8fc98a13d6c29f10600"
lazy = true
    [[pp_lib.download]]
    sha256 = "6fc9f94a7eb38b562176a02e37cdc890f7468c88fefd2c3fc7c82c11dacbc4a6"
    url = "https://raw.githubusercontent.com/spm/PushPull.jl/main/artifacts/pp_lib.tar.gz"

[[pp_lib]]
arch = "x86_64"
os = "windows"
git-tree-sha1 = "320e20d04bc17de8150ec8fc98a13d6c29f10600"
lazy = true
    [[pp_lib.download]]
    sha256 = "6fc9f94a7eb38b562176a02e37cdc890f7468c88fefd2c3fc7c82c11dacbc4a6"
    url = "https://raw.githubusercontent.com/spm/PushPull.jl/main/artifacts/pp_lib.tar.gz"

