[[pp_lib]]
arch = "x86_64"
os = "linux"
git-tree-sha1 = "2126d271764349320f5df3daefcc1b9fec3f7cf3"
lazy = true
    [[pp_lib.download]]
    sha256 = "671eeba23d8c621fd294b1d4a2346ef00d070e857f1412b44512cc40cb487516"
    url = "https://raw.githubusercontent.com/spm/PushPull.jl/main/artifacts/pp_lib.tar.gz"

[[pp_lib]]
arch = "x86_64"
os = "windows"
git-tree-sha1 = "2126d271764349320f5df3daefcc1b9fec3f7cf3"
lazy = true
    [[pp_lib.download]]
    sha256 = "671eeba23d8c621fd294b1d4a2346ef00d070e857f1412b44512cc40cb487516"
    url = "https://raw.githubusercontent.com/spm/PushPull.jl/main/artifacts/pp_lib.tar.gz"

