name = "PushPull"
uuid = "474945d8-a732-43ea-9020-95184c2278ed"
authors = ["John Ashburner"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
